# Generated by Django 3.2.5 on 2025-02-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('nominal', models.PositiveIntegerField()),
                ('real', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inflation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('inflation', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticRegression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocscore', models.PositiveIntegerField()),
                ('modelreport', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Unemployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('unemployment', models.PositiveIntegerField()),
            ],
        ),
    ]
