# Generated by Django 4.2.20 on 2025-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecl_calculations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StageAllocationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='ecl_calculations/stage_allocations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
