# Generated by Django 3.2.5 on 2025-02-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_age', models.PositiveIntegerField()),
                ('person_income', models.PositiveIntegerField()),
                ('person_home_ownership', models.IntegerField(choices=[(0, 'Rent'), (1, 'Own'), (2, 'Mortgage'), (3, 'Other')])),
                ('person_emp_length', models.FloatField()),
                ('loan_intent', models.IntegerField(choices=[(0, 'Debt Consolidation'), (1, 'Education'), (2, 'Home Improvement'), (3, 'Medical'), (4, 'Personal'), (5, 'Venture')])),
                ('loan_grade', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G')])),
                ('loan_amnt', models.PositiveIntegerField()),
                ('loan_int_rate', models.FloatField()),
                ('loan_status', models.IntegerField(choices=[(0, 'Approved'), (1, 'Rejected')])),
                ('loan_percent_income', models.FloatField()),
                ('cb_person_default_on_file', models.BooleanField()),
                ('cb_person_cred_hist_length', models.PositiveIntegerField()),
                ('PD', models.FloatField()),
                ('Stage', models.PositiveIntegerField()),
                ('ECL', models.FloatField()),
                ('ECL_Year_1', models.FloatField(blank=True, null=True)),
                ('ECL_Year_2', models.FloatField(blank=True, null=True)),
                ('ECL_Year_3', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
