# Generated by Django 3.2.5 on 2025-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenario_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticregression',
            name='modelreport',
        ),
        migrations.RemoveField(
            model_name='logisticregression',
            name='rocscore',
        ),
        migrations.AddField(
            model_name='logisticregression',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logisticregression',
            name='image',
            field=models.ImageField(default=0, upload_to='logistic_regression_images/'),
            preserve_default=False,
        ),
    ]
