# Generated by Django 4.2.20 on 2025-03-29 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_statements', '0002_statementofcashflows_statementofchangesinequity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatementOfCashflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='financial_statements/cashflow/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='StatementOfCashflows',
        ),
    ]
