# Generated by Django 3.2.5 on 2025-02-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Obligor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_age', models.PositiveIntegerField()),
                ('person_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('person_home_ownership', models.CharField(choices=[('MORTGAGE', 'Mortgage'), ('RENT', 'Rent'), ('OWN', 'Own'), ('OTHER', 'Other')], max_length=10)),
                ('person_emp_length', models.PositiveIntegerField(help_text='Employment length in years')),
                ('loan_intent', models.CharField(choices=[('DEBT_CONSOLIDATION', 'Debt Consolidation'), ('EDUCATION', 'Education'), ('HOME_IMPROVEMENT', 'Home Improvement'), ('MEDICAL', 'Medical'), ('PERSONAL', 'Personal'), ('VENTURE', 'Venture')], max_length=20)),
                ('loan_grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1)),
                ('loan_amnt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_int_rate', models.DecimalField(decimal_places=2, help_text='Interest rate in %', max_digits=5)),
                ('loan_status', models.CharField(choices=[('CURRENT', 'Current'), ('DEFAULT', 'Default'), ('LATE', 'Late'), ('PAID_OFF', 'Paid Off')], max_length=10)),
                ('loan_percent_income', models.DecimalField(decimal_places=2, help_text='Loan as % of income', max_digits=5)),
                ('cb_person_default_on_file', models.BooleanField(help_text='Has the person defaulted before?')),
                ('cb_person_cred_hist_length', models.PositiveIntegerField(help_text='Credit history length in years')),
            ],
        ),
    ]
